# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-16 18:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20170616_1700'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['post_date']},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['post_date', 'post_time']},
        ),
        migrations.AddField(
            model_name='comment',
            name='post_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='post_time',
            field=models.TimeField(null=True),
        ),
    ]
