# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-17 11:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20170616_1827'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogger',
            name='name',
        ),
        migrations.AlterField(
            model_name='comment',
            name='commenter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
